CREATE TABLE autor (
id_autor TEXT,
nome VARCHAR (100) NOT NULL,
funcao TEXT,
);

INSERT INTO autor (id_autor, nome, funcao)  VALUES
(1, 'Sophia Gomes', 'P.O' ),
(2, 'Anna Clara', 'Scrum Master'),
(3, 'João Vitor Gianoni', 'Time de desenvolvimento' ),
(4, 'Giovanni Gonçalves', 'Time de desenvolvimento' ),
(5, 'Rayssa Lagem', 'Time de desenvolvimento' );


CREATE TABLE noticias (
 id SERIAL PRIMARY KEY,
 titulo VARCHAR(100) NOT NULL,
 descricao TEXT,
 url_noticia VARCHAR(300),
 subtitulo TEXT,
 id_autor INT,
 FOREIGN KEY (id_autor) REFERENCES  autor (id_autor)
);

INSERT INTO noticias (titulo, descricao, url_noticia, subtitulo, id_autor)  VALUES
('Felipe Bardi garante vaga no Mundial de 2025', 'O velocista Felipe Bardi, atleta olímpico do SESI-SP, que treina no SESI Santo André, bateu o índice de 10 segundos cravados nos 100 metros rasos durante o 100° Campeonato Paulista Loterias Caixa de Atletismo Adulto. Com essa marca, que é o exato tempo determinado pela World Athletics como índice para a distância, Bardi se classificou para o Mundial de Atletismo de Tóquio, no Japão, a competição mais importante do calendário internacional em 2025. "Estou feliz por ter feito a marca ainda neste ano já assegurando vaga para o Mundial do ano que vem. Estou contente por encerrar a temporada com este resultado que, confesso, não esperava. Vou seguir trabalhando para que venham boas marcas e mais conquistas em 2025", comemorou o atleta olímpico. Que disputou os Jogos de Paris-2024 e é o atual recordista sul-americano e brasileiro da distância, com a marca de 9.96 segundos. O melhor tempo da carreira de Felipe Bardi até agora foi de 9s96, conquistado durante o Mundial de Atletismo de Budapeste em 2023. no entanto, a sina de não ir bem em campeonatos internacionais ainda permanece. Após a frustração em Paris, onde terminou em 4º lugar em sua bateria (32º no geral) com o tempo de 10s18, Felipe Bardi buscará superar suas marcas pessoais fora do Brasil para tentar chegar longe no Mundial de 2025.', 'https://s2ge.glbimg.com/PaBGqVNgSv76kteya5NYN8dQCQQ=/0x0:2000x1333/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_bc8228b6673f488aa253bbcb03c80ec5/internal_photos/bs/2022/o/W/CahAgbSZmsqnq6Eje0fQ/37be299081cb4a8686a82085ed1507da.jpeg', 'Sonhos não são impossíveis!', 3),
('Parceria entre CRR e SENAI para formação profissional', 'O SENAI-SP e o Grupo CCR assinaram um protocolo de intenções para colaborar em Educação Profissional, Inovação e Tecnologia no setor metroferroviário. O encontro incluiu representantes de sindicatos e associações do setor ferroviário. Josué Gomes, presidente da FIESP e do SENAI-SP, destacou que a parceria promoverá avanços na infraestrutura brasileira e na competitividade da indústria. Miguel Setas, CEO da CCR, enfatizou a importância da neoindustrialização e do engajamento da empresa. A iniciativa é relevante, especialmente com o crescimento de 28,43% no emprego no transporte ferroviário em São Paulo nos últimos 17 anos. Desde 2023, o SENAI-SP já ofereceu mais de 70 cursos para colaboradores da CCR totalizando cerca de 11 mil horas de capacitação.', 'https://i0.wp.com/diariodostrilhos.com/wp-content/uploads/2024/08/viamobilidade-ccr-divulgacao.jpg?fit=800%2C533&ssl=1', 'A parceria entre SENAI-SP e CCR mostra que educação e inovação são essenciais para um futuro urbano sustentável.', 3),
('Equipe de vôlei se classifica para o Regional', 'A equipe de vôlei do SESI alcançou um importante marco ao se classificar para a Regional do campeonato, após uma série de vitórias decisivas na etapa estadual. Com desempenhos consistentes e uma forte estratégia de jogo, o time superou adversários de grande qualidade, destacando-se pela excelência técnica e tática. O treinador da equipe ressaltou a dedicação e o trabalho em equipe como fatores fundamentais para o êxito, além de destacar a importância do preparo físico e mental de cada jogador. Com a classificação garantida, o SESI agora se prepara para os desafios da fase Regional, buscando continuar sua trajetória de sucesso e avançar para as próximas etapas da competição, representando a instituição com muito empenho e garra.', 'https://voleibrasil.s3.amazonaws.com/2024/02/Sesi-Volei-Bauru-recebe-lider-SescFlamengo-scaled.jpg', 'Assim como no vôlei, a força de uma equipe está na união de seus membros, e é com dedicação e esforço coletivo que se alcançam grandes vitórias', 3),
('SENAI-SP capacita 782 docentes durante recesso escolar', 'O SENAI-SP encerrou o primeiro semestre do ano capacitando 782 docentes, formando 57 turmas presencialmente durante o recesso escolar, de 24 a 28 de junho, através do ProEducador, programa de formação de educadores da instituição. O objetivo do treinamento foi aprimorar o conhecimento técnico dos profissionais em 13 diferentes áreas tecnológicas: Alimentos, Automação, Automotiva, Caldeiraria, Eletroeletrônica, Energias Renováveis, Indústria 4.0, Manutenção Industrial, Mecânica, Mecânica de Manutenção, Mecânica de Usinagem, Soldagem e Vestuário. Além disso, sete empresas parceiras – Altus, Knorr, VW do Brasil, Finder, CorelDRAW, SolidCam e Sumig – contribuíram com treinamentos específicos em suas áreas de atuação. A semana de treinamentos ocorreu em 19 unidades SENAI do estado de São Paulo durante o período de recesso escolar, sendo 52 turmas voltadas aos temas técnicos, formando 580 docentes, e cinco turmas voltadas para temas pedagógicos, capacitando mais 202 docentes em práticas educacionais, totalizando os 782 educadores certificados.', 'https://cronos-media.sesisenaisp.org.br//api/media/1-0/files?img=img_81_240822_9fdd9355-3fc6-4621-88dc-48960ba1ddc2_o.jpeg&tipo=p', 'Lute pela sua conquista!', 3),
('Desmatamento na Amazônia atinge níveis alarmantes', 'O desmatamento na Amazônia continua a ser uma preocupação crescente, com áreas vastas de floresta sendo destruídas a cada ano. Especialistas alertam que a perda de cobertura florestal pode ter consequências devastadoras para a biodiversidade e o clima global. Organizações ambientais estão pressionando por políticas mais rigorosas e ações imediatas para proteger a Amazônia. A colaboração entre governos, ONGs e comunidades locais é essencial para combater o desmatamento e promover práticas sustentáveis de uso da terra.', 'https://imazon.org.br/wp-content/uploads/2021/11/Imagem-aerea-feita-em-setembro-de-2021-mostra-desmatamento-em-Labrea-no-Amazonas-Victor-Moriyama-Amazonia-em-Chamas-Divulgacao-Greenpace-1280x720.jpg', 'A destruição da floresta amazônica ameaça não apenas a vida selvagem, mas também o equilíbrio climático do planeta.', 4),
('Aquecimento Global: Um Desafio Urgente', 'O aquecimento global é uma das maiores ameaças enfrentadas pela humanidade hoje. O aumento das temperaturas globais está causando mudanças climáticas significativas, afetando ecossistemas, padrões climáticos e a vida humana. Cientistas e ambientalistas estão pedindo ações imediatas para reduzir as emissões de gases de efeito estufa. A transição para fontes de energia renovável, a conservação de florestas e a promoção de práticas sustentáveis são essenciais para mitigar os impactos do aquecimento global.', 'https://jornal.usp.br/wp-content/uploads/2021/05/20210531_destaque_aquecimentoglobal.png', 'O aquecimento global está acelerando o derretimento das calotas polares, elevando o nível do mar e aumentando a frequência de eventos climáticos extremos.', 4),
('A Importância da Reciclagem: Preservando o Futuro', 'A reciclagem é uma prática essencial para a preservação do meio ambiente e a sustentabilidade do planeta. Ao reciclar, reduzimos a quantidade de resíduos enviados aos aterros sanitários, economizamos recursos naturais e diminuímos a poluição. A conscientização sobre a importância da reciclagem deve ser promovida em todos os níveis da sociedade. Governos, empresas e cidadãos têm um papel crucial na implementação de práticas de reciclagem eficazes. Separar corretamente os resíduos, reutilizar materiais e apoiar políticas de reciclagem são passos fundamentais para um futuro mais sustentável.', 'https://iusnatura.com.br/wp-content/uploads/2020/05/GARRAFA-BLOG.png', 'A reciclagem contribui para a conservação dos recursos naturais, reduzindo a necessidade de extração de matérias-primas e promovendo um ciclo de vida mais sustentável para os produtos.', 4),

('A Importância da Energia Solar: Sustentabilidade e Futuro', 'A energia solar é uma fonte renovável e inesgotável que desempenha um papel crucial na sustentabilidade ambiental. Ao utilizar a energia solar, reduzimos a dependência de combustíveis fósseis, diminuímos a emissão de gases de efeito estufa e promovemos um futuro mais limpo e sustentável. A conscientização sobre a importância da energia solar deve ser promovida em todos os níveis da sociedade. Governos, empresas e cidadãos têm um papel crucial na adoção de tecnologias solares. Investir em painéis solares, apoiar políticas de energia renovável e incentivar a pesquisa e desenvolvimento são passos fundamentais para um futuro mais sustentável.'’', ‘https://omsengenharia.com.br/wp-content/uploads/2016/12/solar-panel-array-1591350-1200x600.jpg', 'A energia solar contribui para a redução da pegada de carbono, aproveitando a luz do sol para gerar eletricidade de forma limpa e eficiente.', 1),

('A Importância dos Biomas: Diversidade e Sustentabilidade', 'Os biomas são grandes áreas geográficas que compartilham características climáticas, vegetação e fauna semelhantes. Eles desempenham um papel crucial na manutenção da biodiversidade e na sustentabilidade ambiental. Cada bioma possui um ecossistema único que contribui para o equilíbrio do planeta. A conscientização sobre a importância dos biomas deve ser promovida em todos os níveis da sociedade. Governos, empresas e cidadãos têm um papel crucial na proteção e conservação dos biomas. Investir em áreas protegidas, apoiar políticas de conservação e incentivar a pesquisa e desenvolvimento são passos fundamentais para um futuro mais sustentável.'’', ‘https://sustentabilidadenoar.com.br/wp-content/uploads/2022/12/capa2-2-800x445.png', 'Os biomas são essenciais para a preservação da biodiversidade e para o equilíbrio dos ecossistemas.', 2),

('Crise Hídrica no Brasil: Desafios e Soluções',  'A crise hídrica no Brasil tem se intensificado nos últimos anos, afetando milhões de pessoas e diversas atividades econômicas. A escassez de água potável e a má gestão dos recursos hídricos são algumas das principais causas desse problema. Especialistas defendem a implementação de políticas públicas mais eficientes e o incentivo ao uso consciente da água. A cooperação entre governos, empresas e a sociedade civil é fundamental para enfrentar a crise hídrica e garantir a sustentabilidade dos recursos hídricos no país.', 'https://www.diariodocentrodomundo.com.br/wp-content/uploads/2024/09/15112db4-60dc-4c52-8115-037204b420b7.jpg', 'A falta de água potável ameaça a saúde pública e a segurança alimentar, exigindo medidas urgentes e eficazes.', 1),

('Sustentabilidade: Caminhos para um Futuro Melhor', 'A sustentabilidade é um tema crucial nos dias de hoje, envolvendo práticas que visam preservar o meio ambiente e garantir recursos para as futuras gerações. A adoção de hábitos sustentáveis é essencial para minimizar os impactos ambientais. Especialistas destacam a importância de políticas públicas que incentivem práticas sustentáveis, como o uso de energias renováveis, a reciclagem e a conservação dos recursos naturais. A colaboração entre governos, empresas e a sociedade é fundamental para promover a sustentabilidade e garantir um futuro melhor para todos.', 'https://www.portalsolar.com.br/_next/image?url=https%3A%2F%2Fportalsolar-images.s3.us-east-2.amazonaws.com%2Finstitucional-and-info-production%2Fimages%2F13301453-bc8a-4105-94d3-3e6a885a0e68%2Fo-que-e-sustentabilidade.jpg&w=3840&q=100', 'A sustentabilidade é a chave para um futuro mais saudável e equilibrado, onde o desenvolvimento econômico e a preservação ambiental caminham juntos.', 2),

('A Importância da Geografia na Educação', 'A geografia é uma disciplina fundamental que nos ajuda a compreender o mundo em que vivemos. Ela nos permite analisar a relação entre o ambiente físico e as atividades humanas, promovendo uma visão integrada e crítica do espaço geográfico. A educação geográfica deve ser valorizada em todos os níveis de ensino. Ela desenvolve habilidades de análise espacial, pensamento crítico e compreensão das questões ambientais e sociais. Professores, alunos e a comunidade em geral devem reconhecer a importância da geografia para a formação de cidadãos conscientes e responsáveis.', 'https://saci.org.br/wp-content/uploads/2018/09/geografia.jpg', 'A geografia é essencial para entender as dinâmicas territoriais e a interação entre sociedade e natureza.', 2),

('Mudanças Climáticas: Desafios e Soluções', 'As mudanças climáticas representam um dos maiores desafios do nosso tempo. Elas são causadas principalmente pela emissão de gases de efeito estufa, resultantes de atividades humanas como a queima de combustíveis fósseis e o desmatamento. Governos, empresas e indivíduos precisam trabalhar juntos para mitigar os efeitos das mudanças climáticas. Isso inclui a redução das emissões de carbono, a promoção de energias renováveis e a implementação de políticas de conservação ambiental.', 'https://faculdadevicentina.com.br/cdn/shop/articles/photorealistic-earth-planet.jpg?v=1727099881&width=1100', 'Combater as mudanças climáticas é essencial para garantir a sobrevivência do nosso planeta e das futuras gerações.', 5),

('Geografia Urbana no Brasil: Desafios e Perspectivas', 'A geografia urbana no Brasil é caracterizada por uma grande diversidade de paisagens e dinâmicas sociais, que vão desde metrópoles densamente povoadas até cidades de médio porte. A gestão sustentável dos espaços urbanos e a melhoria da qualidade de vida nas cidades são alguns dos principais desafios enfrentados. Especialistas defendem a implementação de políticas públicas que promovam a inclusão social e econômica das populações urbanas, além do incentivo ao planejamento urbano sustentável. A cooperação entre governos, empresas e a sociedade civil é fundamental para enfrentar os desafios da geografia urbana e garantir um futuro próspero para as cidades brasileiras.', 'https://www.uninter.com/noticias/wp-content/uploads/2020/01/noticias_curitiba.jpg', 'A valorização do espaço urbano é essencial para o desenvolvimento sustentável e a promoção da qualidade de vida.', 5),

('Geografia Rural no Brasil: Desafios e Perspectiva', 'A geografia rural no Brasil é marcada por uma diversidade de paisagens e atividades econômicas, que vão desde a agricultura familiar até grandes propriedades agroindustriais. A gestão sustentável dos recursos naturais e a melhoria da qualidade de vida no campo são alguns dos principais desafios enfrentados. Especialistas defendem a implementação de políticas públicas que promovam a inclusão social e econômica das populações rurais, além do incentivo à agricultura sustentável. A cooperação entre governos, empresas e a sociedade civil é fundamental para enfrentar os desafios da geografia rural e garantir um futuro próspero para o campo brasileiro.', 'https://cdn.pixabay.com/photo/2019/07/27/11/21/campaign-4366556_960_720.jpg', 'A valorização do espaço rural é essencial para o desenvolvimento sustentável e a preservação das tradições culturais.', 1),

('A Importância da Gestão de Recursos Naturais', 'A gestão de recursos naturais é crucial para garantir a sustentabilidade e o equilíbrio ambiental. Ela envolve o planejamento e a utilização responsável dos recursos naturais, promovendo práticas que minimizem o impacto ambiental e preservem os ecossistemas. A educação sobre a gestão de recursos naturais deve ser promovida em todos os níveis de ensino. Ela desenvolve habilidades de planejamento ambiental, pensamento crítico e compreensão das questões ecológicas e sociais. Professores, alunos e a comunidade em geral devem reconhecer a importância da gestão de recursos naturais para a formação de cidadãos conscientes e responsáveis.', 'https://www.portalsolar.com.br/_next/image?url=https%3A%2F%2Finstitucional-and-info-production.s3.us-east-2.amazonaws.com%2Fimages%2Fa9720da4-f23b-481f-aec8-0baaf3a517f3%2Fclassificacao-dos-recursos-naturais.webp&w=3840&q=100', 'A gestão de recursos naturais é essencial para garantir a sustentabilidade e a preservação dos ecossistemas.', 2);


SELECT * 
FROM noticias 
INNER JOIN autor ON noticias.id_autor = autor.id_autor;